---
uid: rule:github_webhook
name: github_webhook
ref: nufuk.github_webhook
description: run on a merge with the main repo
pack: nufuk
type:
  ref: standard
  parameters: {}
trigger:
  type: core.st2.webhook
  parameters:
    url: "mainmerge"
  description: Triggers whenever there is merge to main.
criteria: {}
action:
  ref: nufuk.github_webhook
  description: trigger packs.install of main
enabled: true
