---
uid: rule:github_webhook
name: github_webhook
ref: nufuk.github_webhook
description: run on a merge with the main repo
pack: nufuk
type:
  ref: standard
  parameters: {}
trigger:
  type: core.st2.webhook
  parameters:
    url: "mainmerge"
  description: Triggers whenever there is merge to main.
criteria: 
    trigger.body:
      type: contains
      pattern: "refs/heads/main"
action:
  ref: nufuk.github_webhook
  description: trigger packs.install of main
  parameters:
    github_data: "{{ trigger.body.payload }}"
enabled: true
