---
uid: rule:github_webhook
name: github_webhook
ref: nufuk.github_webhook
description: This rule gets triggered from github when a branch is merged main
pack: nufuk
type:
  ref: standard
  parameters: {}
trigger:
  type: core.st2.webhook
  parameters:
    url: "mainmerge"
  description: Triggers whenever there is merge to main.
criteria:
  trigger.body.ref:
    type: eq
    pattern: "refs/head/main"
action:
  ref: nufuk.github_webhook
  description: trigger installation of main branch
  parameters:
    github_data: "{{ trigger.body }}"
enabled: true
