---
uid: rule:nufuk:package_upgrade_rocky
name: package_upgrade_rocky
ref: nufuk.package_upgrade_rocky
description: upgrades the rocky packages once a week
pack: nufuk
type:
  ref: standard
  parameters: {}
trigger:
  type: core.st2.CronTimer
  parameters:
    day: '*'
    day_of_week: '1'
    hour: '4'
    minute: '30'
    month: '*'
    second: '0'
    timezone: 'CET'
    week: '*'
    year: '*'
  description: Triggers whenever current time matches the specified time constaints like a UNIX cron scheduler.
criteria: {}
action:
  ref: nufuk.package_upgrade_rocky
  description: nufuk package_upgrade_rocky
enabled: true
