---
uid: rule:nufuk:kernel_upgrade_debian
name: kernel_upgrade_debian
ref: nufuk.kernel_upgrade_debian
description: upgrades the Debian Kernel once a month
pack: nufuk
type:
  ref: standard
  parameters: {}
trigger:
  type: core.st2.CronTimer
  parameters:
    day: '*'
    day_of_week: '0'
    hour: '4'
    minute: '0'
    month: '*'
    second: '0'
    timezone: 'CET'
    week: '4'
    year: '*'
  description: Triggers whenever current time matches the specified time constaints like a UNIX cron scheduler.
criteria: {}
action:
  ref: nufuk.kernel_upgrade_debian
  description: nufuk kernel_upgrade_debian
  parameters:
    grafana_data: ''
enabled: true
